'use client';

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface AnalysisReportData {
  sessionId: string;
  fileName: string;
  fileType: string;
  analysisDate: string;
  verdict: string;
  confidence: number;
  severity: number;
  deepfakeType: string;
  bioSignals: {
    eyeBlink: {
      status: string;
      rate: number;
      confidence: number;
    };
    microExpressions: {
      status: string;
      confidence: number;
    };
    rppg: {
      status: string;
      bpm: number;
      confidence: number;
    };
  };
  explainability: string[];
  suspiciousFrames: Array<{
    timestamp: string;
    score: number;
    description: string;
  }>;
  deepfakeTypes: {
    faceSwap: number;
    lipSync: number;
    expressionManipulation: number;
    temporalInconsistency: number;
  };
}

export const generatePDFReport = async (reportData: AnalysisReportData) => {
  // Create a new jsPDF instance
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(22);
  doc.setTextColor(32, 129, 226); // Blue color
  doc.text('BioSecure Analysis Report', 20, 20);
  
  // Add subtitle
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`Session ID: ${reportData.sessionId}`, 20, 35);
  
  // Add file info
  doc.setFontSize(14);
  doc.text('File Information', 20, 50);
  doc.setFontSize(12);
  doc.text(`File Name: ${reportData.fileName}`, 20, 60);
  doc.text(`File Type: ${reportData.fileType}`, 20, 70);
  doc.text(`Analysis Date: ${reportData.analysisDate}`, 20, 80);
  
  // Add verdict section
  doc.setFontSize(14);
  doc.text('Analysis Verdict', 20, 100);
  doc.setFontSize(12);
  doc.text(`Verdict: ${reportData.verdict}`, 20, 110);
  doc.text(`Confidence: ${reportData.confidence}%`, 20, 120);
  doc.text(`Severity Score: ${reportData.severity}/10`, 20, 130);
  doc.text(`Deepfake Type: ${reportData.deepfakeType}`, 20, 140);
  
  // Add bio signals section
  doc.setFontSize(14);
  doc.text('Biological Signal Analysis', 20, 160);
  doc.setFontSize(12);
  doc.text(`Eye Blink: ${reportData.bioSignals.eyeBlink.status} (${reportData.bioSignals.eyeBlink.confidence}% confidence)`, 20, 170);
  doc.text(`Micro-Expressions: ${reportData.bioSignals.microExpressions.status} (${reportData.bioSignals.microExpressions.confidence}% confidence)`, 20, 180);
  doc.text(`rPPG: ${reportData.bioSignals.rppg.status} (${reportData.bioSignals.rppg.bpm} BPM, ${reportData.bioSignals.rppg.confidence}% confidence)`, 20, 190);
  
  // Add explainability section
  doc.setFontSize(14);
  doc.text('Analysis Explanation', 20, 210);
  doc.setFontSize(10);
  let explainabilityY = 220;
  reportData.explainability.forEach((explanation, index) => {
    if (explainabilityY > 280) { // If we're near the bottom of the page
      doc.addPage(); // Add a new page
      explainabilityY = 20; // Reset Y position
      doc.setFontSize(14);
      doc.text('Analysis Explanation (continued)', 20, explainabilityY);
      explainabilityY += 10;
      doc.setFontSize(10);
    }
    doc.text(`• ${explanation}`, 20, explainabilityY);
    explainabilityY += 8;
  });
  
  // Add deepfake types section
  doc.addPage();
  doc.setFontSize(14);
  doc.text('Deepfake Type Analysis', 20, 20);
  doc.setFontSize(12);
  doc.text(`Face Swap Score: ${reportData.deepfakeTypes.faceSwap}`, 20, 30);
  doc.text(`Lip Sync Score: ${reportData.deepfakeTypes.lipSync}`, 20, 40);
  doc.text(`Expression Manipulation Score: ${reportData.deepfakeTypes.expressionManipulation}`, 20, 50);
  doc.text(`Temporal Inconsistency Score: ${reportData.deepfakeTypes.temporalInconsistency}`, 20, 60);
  
  // Add suspicious frames
  doc.setFontSize(14);
  doc.text('Suspicious Frames', 20, 80);
  doc.setFontSize(10);
  let frameY = 90;
  reportData.suspiciousFrames.forEach((frame, index) => {
    if (frameY > 280) { // If we're near the bottom of the page
      doc.addPage(); // Add a new page
      frameY = 20; // Reset Y position
      doc.setFontSize(14);
      doc.text('Suspicious Frames (continued)', 20, frameY);
      frameY += 10;
      doc.setFontSize(10);
    }
    doc.text(`${frame.timestamp} - Score: ${frame.score} - ${frame.description}`, 20, frameY);
    frameY += 8;
  });
  
  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.text(`Page ${i} of ${pageCount}`, 200, 290);
    doc.text('Generated by BioSecure AI', 20, 290);
  }
  
  // Save the PDF
  doc.save(`biosecure-report-${reportData.sessionId}.pdf`);
};

// Alternative method to generate PDF from HTML content
export const generateHTMLPDF = async (elementId: string, fileName: string) => {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`);
  }
  
  const canvas = await html2canvas(element);
  const imgData = canvas.toDataURL('image/png');
  const pdf = new jsPDF('p', 'mm', 'a4');
  const imgWidth = 210; // A4 width in mm
  const pageHeight = 297; // A4 height in mm
  const imgHeight = (canvas.height * imgWidth) / canvas.width;
  let heightLeft = imgHeight;
  let position = 0;

  pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
  heightLeft -= pageHeight;

  while (heightLeft >= 0) {
    position = heightLeft - imgHeight;
    pdf.addPage();
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
  }

  pdf.save(fileName);
};